"""link_transactions_to_bills

Revision ID: 320932b45f52
Revises: 69d3920b8fd5
Create Date: 2026-08-04 12:15:09.616619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320932b45f52'
down_revision: Union[str, Sequence[str], None] = '69d3920b8fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('sale_id', sa.Uuid(), nullable=True))
    op.add_column('payment_transactions', sa.Column('purchase_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payment_transactions_purchase_id'), 'payment_transactions', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_sale_id'), 'payment_transactions', ['sale_id'], unique=False)
    op.create_foreign_key(None, 'payment_transactions', 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_transactions', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_payment_transactions_sale_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_purchase_id'), table_name='payment_transactions')
    op.drop_column('payment_transactions', 'purchase_id')
    op.drop_column('payment_transactions', 'sale_id')
    # ### end Alembic commands ###
