"""Add driver_name and vehicle_number to purchase and sale

Revision ID: c85f1ecd6ecb
Revises: cb8a99f38f07
Create Date: 2026-07-24 15:26:22.041166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85f1ecd6ecb'
down_revision: Union[str, Sequence[str], None] = 'cb8a99f38f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_ta', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('unit_type', sa.Enum('KG', 'UNIT', name='unittype'), nullable=False),
    sa.Column('available_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_items_item_id'), 'purchase_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_item_id'), 'sale_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.add_column('expense_categories', sa.Column('name_ta', sa.String(length=255), nullable=False))
    op.add_column('expense_categories', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('expense_categories_name_key'), 'expense_categories', type_='unique')
    op.create_unique_constraint(None, 'expense_categories', ['name_en'])
    op.create_unique_constraint(None, 'expense_categories', ['name_ta'])
    op.drop_column('expense_categories', 'name')
    op.add_column('purchases', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('purchases', 'birds_per_box')
    op.drop_column('purchases', 'purchase_amount')
    op.drop_column('purchases', 'actual_birds')
    op.drop_column('purchases', 'weighbridge_weight')
    op.drop_column('purchases', 'net_weight')
    op.drop_column('purchases', 'remarks')
    op.drop_column('purchases', 'average_weight')
    op.drop_column('purchases', 'total_boxes')
    op.drop_column('purchases', 'purchase_rate')
    op.add_column('sales', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('sales', 'birds_per_box')
    op.drop_column('sales', 'weight_amount')
    op.drop_column('sales', 'weight_rate')
    op.drop_column('sales', 'box_rate')
    op.drop_column('sales', 'boxes')
    op.drop_column('sales', 'box_amount')
    op.drop_column('sales', 'total_invoice_amount')
    op.drop_column('sales', 'actual_birds')
    op.drop_column('sales', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('actual_birds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('total_invoice_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('box_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('boxes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('box_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('weight_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('weight_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('birds_per_box', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('sales', 'total_amount')
    op.add_column('purchases', sa.Column('purchase_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('total_boxes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('average_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('net_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('weighbridge_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('actual_birds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('purchase_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('birds_per_box', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchases', 'total_amount')
    op.add_column('expense_categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense_categories', type_='unique')
    op.drop_constraint(None, 'expense_categories', type_='unique')
    op.create_unique_constraint(op.f('expense_categories_name_key'), 'expense_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('expense_categories', 'name_en')
    op.drop_column('expense_categories', 'name_ta')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_item_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_item_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
