"""Add min_stock_alert

Revision ID: e6bef085a7d1
Revises: 320932b45f52
Create Date: 2026-08-05 12:07:14.420377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bef085a7d1'
down_revision: Union[str, Sequence[str], None] = '320932b45f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('items', sa.Column('min_stock_alert', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'min_stock_alert')
    # ### end Alembic commands ###
